### ISSUE TITLE
DatepickerOptions is not working

### ISSUE THREAD

**Issue by MS-Harine** [shangyilim/ionic2-date-picker#29]
On my environment, minimum date and maximum date function is not working.. I follow README, but..
I remember that version 1.0.0 is working, but when I update to version 1.1.0, it has something strange.

**Comment by shangyilim** [comment]
Hello, do you mind posting a sample code so I can replicate the issue?
Thanks!

On 11 Feb 2018 4:16 p.m., "MS-Harine" <notifications@github.com> wrote:

On my environment, minimum date and maximum date function is not working..
I follow README, but..
I remember that version 1.0.0 is working, but when I update to version
1.1.0, it has something strange.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shangyilim/ionic2-date-picker/issues/29>, or mute the
thread

**Comment by MS-Harine** [comment]
`showCalendar() {
    var now = new Date();
    let datePickerOption: DatePickerOption = {
      minimumDate: now,
      maximumDate: new Date(now.getFullYear(), now.getMonth() + 1, now.getDate())
    }

    const dateSelected = this.datePickerProvider.showCalendar(this.modalCtrl, datePickerOption);
    dateSelected.subscribe(date => {this.showChatroom(date);});
  }`

This is my code. Is there something strange?

**Comment by shangyilim** [comment]
i have fixed this issue with 1.1.2,
